version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres
  usuario:
    image: loja/usuario
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
